console.log("Welcome to Spotify");
let songs=[
    {songName:"Salam e Ishq", filepath: "Song/1.mp3" , coverpath: "file/1.jgp" },
    {songName:"Salam e Ishq", filepath: "Song/1.mp3" , coverpath: "file/1.jgp" },
    {songName:"Salam e Ishq", filepath: "Song/1.mp3" , coverpath: "file/1.jgp" },
    {songName:"Salam e Ishq", filepath: "Song/1.mp3" , coverpath: "file/1.jgp" },
    {songName:"Salam e Ishq", filepath: "Song/1.mp3" , coverpath: "file/1.jgp" },
    {songName:"Salam e Ishq", filepath: "Song/1.mp3" , coverpath: "file/1.jgp" },


]
let audioElement = new Audio('1.mp3');